### ISSUE TITLE
No option to select  cert root at hickory_server

### ISSUE THREAD

**Issue by LuckyTurtleDev** [hickory-dns/hickory-dns#2067]
**Describe the bug**
No option to select  cert root at hickory_server. Looks like it was missing to forward the feature flags for hickory-resolver.

**To Reproduce**
Cargo.toml
```toml
trust-dns-proto = {  package = "hickory-proto", version = "0.24", default-features = false }
trust-dns-server = { package = "hickory-server", version = "0.24", default-features = false,  features = ["dnssec-ring", "dns-over-h3" ,"dns-over-rustls", "dns-over-https-rustls", "dns-over-quic"] }
```
Make a dot request using trust-dns-server(forward config) and it will fail with the following error message:
```
hickory_proto::xfer::dns_exchange               > stream errored while connecting error=io error: tls error: invalid peer certificate: UnknownIssuer
```

**Expected behavior**
Opiton to enable cert root

**System:**
 - OS: [Arch]
 - Architecture: [x86_64]
 - Version [0.24.0]
 - rustc version: [rustc 1.73.0 (cc66ad468 2023-10-03)]

**Version:**
Crate: [hickory-server]
Version: [0.24.0]

**Additional context**
Current work around:
```toml
trust-dns-proto = {  package = "hickory-proto", version = "0.24", default-features = false }
trust-dns-server = { package = "hickory-server", version = "0.24", default-features = false,  features = ["dnssec-ring", "dns-over-h3" ,"dns-over-rustls", "dns-over-https-rustls", "dns-over-quic"] }
hickory-resolver = { version = "0.24.0", default-features = false, features = ["webpki-roots"] }
```
