### ISSUE TITLE
On 0.25.0-alpha.2, setting validate=true does not validate DNSSEC

### ISSUE THREAD

**Issue by msrd0** [hickory-dns/hickory-dns#2428]
**Describe the bug**
DNSSEC isn't checked properly.

**To Reproduce**
Start hickory-dns with the following config:

```toml
listen_port = 53
listen_addrs_ipv4 = ["127.0.0.1"]
listen_addrs_ipv6 = ["::1"]

[[zones]]
zone = "."
zone_type = "Forward"

[zones.stores]
type = "forward"

[zones.stores.options]
validate = true

[[zones.stores.name_servers]]
socket_addr = "1.1.1.1:853"
protocol = "tls"
tls_dns_name = "cloudflare-dns.com"
trust_nx_responses = false

[[zones.stores.name_servers]]
socket_addr = "1.0.0.1:853"
protocol = "tls"
tls_dns_name = "cloudflare-dns.com"
trust_nx_responses = false

# dns101.comcast.net, for querying dnssec-failed.org
[[zones.stores.name_servers]]
socket_addr = "69.252.250.103:53"
protocol = "udp"
trust_nx_responses = false
```

Then, query `dnssec-failed.org` and observe that a record is returned. Note that cloudflare (1.1.1.1) does DNSSEC validation, so I added a nameserver from the whois response to be sure that hickory actually receives a record to validate. https://dnsviz.net/d/dnssec-failed.org/dnssec/ shows that the domain has a bogus dnssec record.

**Expected behavior**
I expect to (a) not receive any records, and (b) expect to receive some error indication like a SERVFAIL response.

**System:**
 - OS: I use arch btw
 - Architecture: x86_64
 - Version: Linux 6.10.7-arch1-1
 - rustc version: 1.80.1 (376290515 2024-07-16)

**Version:**
Crate: hickory-dns binary
Version: 0.25.0-alpha.2
