### ISSUE TITLE
Linux configuration without a `/etc/resolv.conf` is not working

### ISSUE THREAD

**Issue by stormshield-gt** [hickory-dns/hickory-dns#2959]
**Describe the bug**
In my current Linux configuration, I don't have a `/etc/resolv.conf` which makes failed the hickory resolver.

The Linux [man page](https://www.man7.org/linux/man-pages/man5/resolver.5.html) said that if this file does not exist, only the name server on the local machine will be queried, so I think my configuration is valid.

**To Reproduce**

You need to have a machine without `/etc/resolv.conf`.

```toml
# Cargo.toml
[package]
name = "playground"
version = "0.0.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.15", features = ["rustls-tls", "hickory-dns"] }
rustls = "0.23.26"
tokio = { version = "1.44.2", features = ["full"] }
```

```rust
// main.rs
#[tokio::main]
async fn main() {
    let body = reqwest::get("https://www.rust-lang.org")
        .await
        .unwrap()
        .text()
        .await
        .unwrap();

    println!("body = {body:?}")
}
```

I get this error :

```sh
thread 'main' panicked at src/main.rs:5:10:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: "https://www.rust-lang.org/", source: hyper_util::client::legacy::Error(Connect, ConnectError("dns error", HickoryDnsSystemConfError(ResolveError { kind: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }) }))) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

But if i deactivate hickory DNS, it will work just fine.

```rust
#[tokio::main]
async fn main() {
    let body = reqwest::ClientBuilder::new()
        .no_hickory_dns()
        .build()
        .unwrap()
        .get("https://www.rust-lang.org")
        .send()
        .await
        .unwrap()
        .text()
        .await
        .unwrap();

    println!("body = {body:?}")
}
```

Manually adding a `/etc/resolv.conf` will solve the problem, but I require tweaking the local DNS configuration, which is not always possible.

```sh
sudo sh -c 'echo "nameserver 127.0.0.1" > /etc/resolv.conf'
```

**Expected behavior**

I would have expected to work out of the box, even if `/etc/resolv.conf` doesn't exist.

**System:**
 - OS: Linux
 - Architecture: x86_64

**Version:**
Crate:  resolver
Version: 0.24.4
